Repository miIlicon/wf-front, pull requests merged in 2023-10, with the labels that each got.

#92 Bugfix/83/live re remove
  src/components/common/CreateSection.tsx
  src/components/common/PageTitle.tsx
  src/components/common/components.tsx
  src/images/emoji/plane.svg
  src/pages/BoothPage.tsx
  src/pages/Detail/Detail.tsx
  src/pages/Inform/Notice.tsx
  src/pages/Inform/QandA.tsx
  src/pages/InformPage.tsx
  src/pages/ProgramPage.tsx
Labels: 🐛 BugFix

#98 feat : 게시글 API 최종 연동 및 자동 이벤트 상태 값 부여 로직 추가, 예정 중인 이벤트 파라미터 추가 (#96)
  src/@types/typs.ts
  src/components/common/Card.tsx
  src/components/common/CardList.tsx
  src/components/common/EventStatusButton.tsx
  src/components/main/EventTemplate.tsx
  src/pages/BoothPage.tsx
  src/pages/Detail/Detail.tsx
  src/pages/Editor.tsx
  src/pages/ProgramPage.tsx
Labels: 🚀 Feat

#99 인기게시물 API 연동 및 더 보러가기 페이지 연결 (#85)
  src/@types/typs.ts
  src/components/main/EventTemplate.tsx
  src/pages/Index/Index.tsx
Labels: 🚀 Feat

#107 대나무 숲 모바일 환경 대응 및 대화 더보기 API 연동 (+ 예외 처리) (#106)
  public/index.html
  src/components/common/Banner.tsx
  src/components/common/components.tsx
  src/components/common/test.md
  src/components/community/ChatBox.tsx
  src/components/community/ChatList.tsx
  src/components/community/InputBox.tsx
  src/components/community/Intro.tsx
  src/index.css
Labels: 🚀 Feat, 👀 Modify

#109 feat : 메인 페이지 디자인 및 UI 일부 수정 (#108)
  src/components/common/CalendarNotice.tsx
  src/components/community/ChatList.tsx
  src/components/main/Title.tsx
  src/pages/BoothPage.tsx
  src/pages/Detail/Detail.tsx
  src/pages/Index/Index.tsx
Labels: 🚀 Feat, 👀 Modify

#114 Fix/113/modify token method
  package.json
  public/index.html
  src/@types/typs.ts
  src/components/common/Banner.tsx
  src/components/common/CalendarNotice.tsx
  src/components/common/Card.tsx
  src/components/common/DetailCard.tsx
  src/components/common/NotData.tsx
  src/components/common/Notice.tsx
  src/components/community/ChatBox.tsx
  src/components/community/ChatList.tsx
  src/components/community/InputBox.tsx
  src/components/community/Intro.tsx
  src/components/main/Introduce.tsx
  src/components/main/SlideCard.tsx
  src/components/main/Title.tsx
  src/components/main/ViewTimeTable.tsx
  src/hooks/ImagePreload.tsx
  src/images/community/close.svg
  src/index.tsx
  src/pages/BoothPage.tsx
  src/pages/Editor.tsx
  src/pages/Login/Login.tsx
  src/pages/ProgramPage.tsx
  src/styles/GlobalStyles.tsx
  yarn.lock
Labels: 🐛 BugFix, 🚀 Feat, 👀 Modify

#115 공지사항 API 연동 및 공지사항 등록 이벤트 적용 (#105)
  src/@types/typs.ts
  src/pages/Inform/Notice.tsx
Labels: 🚀 Feat

#118 feat : 배너 링크 연결 (#117)
  src/components/common/Banner.tsx
  src/components/main/Introduce.tsx
  src/hooks/ImagePreload.tsx
  src/images/main/people.webp
Labels: 🚀 Feat

#119 feat : 프론트엔드 프로덕션 환경으로 API 변경 (#70)
  package.json
Labels: 🚀 Feat, 👀 Modify

#120 feat : 프론트엔드 프로덕션 환경으로 API 변경 (#70)
  src/pages/Login/Login.tsx
  src/utils/api.tsx
Labels: 🦠 bug

#122 feat : Vercel 프록시 설정 (#70)
  vercel.json
Labels: 🦠 bug, 👀 Modify

#121 타임테이블 컴포넌트 개발
  src/@types/typs.ts
  src/components/common/Modal.tsx
  src/components/common/ModalPortal.tsx
  src/components/main/TimeTable.tsx
  src/components/main/ViewTimeTable.tsx
Labels: 🚀 Feat

#124 bugfix : 배포 후 발생하는 에러 수정 및 처리 (#123)
  src/components/community/ChatBox.tsx
  src/pages/Editor.tsx
Labels: 🦠 bug, 🐛 BugFix, 👀 Modify

#125 feat : 디테일 페이지 추가 수정 (#123)
  src/components/common/CalendarNotice.tsx
  src/components/common/LoadComponent.tsx
  src/components/common/Welcome.tsx
  src/pages/Detail/Detail.tsx
Labels: 🚀 Feat, 👀 Modify

#128 feat : 환경 변수 설정 및 채널톡 API 추가, 사용성 패치 (#127)
  src/App.css
  src/App.tsx
  src/components/common/Card.tsx
  src/components/common/DetailCard.tsx
  src/components/common/Welcome.tsx
  src/components/community/ChatList.tsx
  src/pages/Detail/Detail.tsx
  src/utils/ChannelService.ts
  src/utils/api.tsx
Labels: 🚀 Feat, 👀 Modify

#129 검색 API 연동
  src/@types/typs.ts
  src/components/main/Search.tsx
Labels: 🚀 Feat

#131 bugfix : 첫 렌더시에 대나무 숲에서 대화 더보기가 보이지 않는 현상 수정 (#130)
  public/index.html
  src/components/common/Card.tsx
  src/components/community/ChatList.tsx
  src/index.css
  src/styles/GlobalStyles.tsx
Labels: 🦠 bug, 🐛 BugFix

#132 bugfix : 모바일 환경에서 상세화면의 댓글이 잘려보이는 현상 수정 (#130)
  src/pages/Detail/Detail.tsx
Labels: 🦠 bug, 🐛 BugFix

#133 공지사항 등록, 삭제 기능 추가 및 관리자 아이콘 등록
  public/profile/abby.png
  public/profile/blin.png
  public/profile/dori.png
  public/profile/horang.png
  public/profile/judy.png
  src/@types/typs.ts
  src/data/profile.json
  src/images/profile/horang.png
  src/pages/Inform/Notice.tsx
Labels: 🚀 Feat, 👀 Modify

#138 feat : 방문자 조회 데이터 통신 연동 (#137)
  src/pages/Index/Index.tsx
  src/pages/Login/Login.tsx
Labels: 🚀 Feat

#142 안내사항 데이터 추가
  src/data/QandA.json
  src/pages/Inform/Bus.tsx
  src/pages/Inform/QandA.tsx
Labels: 👀 Modify

#143 Feature/140/change menu
  src/components/common/Header.tsx
  src/images/menu.svg
Labels: 🚀 Feat, 👀 Modify

#144 모바일 카테고리 UI 변경
  src/pages/CategoryPage.tsx
Labels: 👀 Modify

#150 안내사항 페이지 UI 변경
  src/pages/Inform/Notice.tsx
  src/pages/Inform/QandA.tsx
Labels: 👀 Modify

#149 메인페이지에서 최근 공지사항을 가져오지 못하는 오류 해결
  src/components/main/Search.tsx
Labels: 🐛 BugFix

#152 Bugfix/151/rebuild token
  src/components/community/ChatBox.tsx
  src/pages/CategoryPage.tsx
  src/pages/Inform/Notice.tsx
Labels: 🦠 bug, 🐛 BugFix

#154 공지사항 토큰 재발급 로직 추가
  src/pages/Inform/Notice.tsx
Labels: 🦠 bug, 🐛 BugFix

#156 bugfix : 토큰 재발급 로직을 변경합니다 (#155)
  src/components/community/ChatBox.tsx
  src/components/community/InputBox.tsx
  src/pages/Editor.tsx
Labels: 🦠 bug

#158 bugfix : 공지사항 토큰 재발급 로직 추가 (#154)
  src/pages/Inform/Notice.tsx
Labels: 🦠 bug

#161 feat : 대나무 숲 욕설 필터링 적용 (#160)
  src/App.tsx
  src/components/community/ChatBox.tsx
  src/components/community/InputBox.tsx
Labels: 🚀 Feat

#164 feat : 토큰 만료시간을 프론트엔드에서 페이로드로 처리 및 재발급 로직 추가 수정 (#163)
  package.json
  src/components/community/ChatBox.tsx
  src/components/community/InputBox.tsx
  src/pages/Editor.tsx
  src/pages/Inform/Notice.tsx
  src/pages/Login/Login.tsx
  src/utils/cookies.ts
  yarn.lock
Labels: 🚀 Feat, 👀 Modify

#165 Modify/163
  src/components/community/ChatBox.tsx
  src/pages/Editor.tsx
  src/pages/Inform/Notice.tsx
Labels: 🚀 Feat, 👀 Modify

#168 feat : 게시글 삭제 API 연동 및 상세 게시글 툴바 생성 (#167)
  src/components/common/CreateSection.tsx
  src/components/common/DetailSectionBtn.tsx
  src/images/detail/back.svg
  src/images/detail/delete.svg
  src/pages/Detail/Detail.tsx
Labels: 🚀 Feat, 👀 Modify

#169 데이터 추가 및 수정
  public/timetable/timetable1.png
  public/timetable/timetable2.png
  src/components/main/CurrentEvent.tsx
  src/components/main/TimeTable.tsx
  src/data/artist.json
  src/data/timetable.json
  src/pages/BoothPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/Index/Index.tsx
  src/pages/Inform/Notice.tsx
  src/pages/ProgramPage.tsx
Labels: 👀 Modify

#172 feat : 메인 화면에서의 가로 스크롤 스타일 추가 (#171)
  src/components/main/EventTemplate.tsx
Labels: 🚀 Feat

#173 전체 타임테이블 가로스크롤 제거
  src/components/main/TimeTable.tsx
Labels: 🦠 bug, 🐛 BugFix

#174 fix : 모바일 환경에서 뒤로가기 폰트 크기 수정 (#171)
  src/components/common/DetailSectionBtn.tsx
Labels: 👀 Modify

#175 fix : 모바일 환경에서 크기 수정 (#171)
  src/pages/Detail/Detail.tsx
Labels: 🦠 bug, 🐛 BugFix

#177 카테고리명 변경
  src/components/common/Header.tsx
  src/data/category.json
  src/pages/BoothPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/Index/Index.tsx
  src/pages/ProgramPage.tsx
Labels: 👀 Modify

#178 docs : UPDATE READMD
  README.md
Labels: 📝 Docs
