Repository miIlicon/wf-front, pull requests merged in 2023-09, with the labels that each got.

#58 feat: 프로그램, 축제 부스 목록 페이지 개발 (#57)
  src/@types/typs.ts
  src/components/common/Card.tsx
  src/components/common/CardList.tsx
  src/components/common/EventStatusButton.tsx
  src/pages/BoothPage.tsx
  src/pages/Detail/Detail.tsx
  src/pages/FestivalPage.tsx
Labels: 🚀 Feat

#60 feat: 안내사항 페이지 개발 (#59)
  src/@types/typs.ts
  src/data/QandA.json
  src/data/profile.json
  src/images/nextButton.svg
  src/images/prevButton.svg
  src/images/profile/horang.png
  src/images/profile/judy.png
  src/pages/Inform/Bus.tsx
  src/pages/Inform/Notice.tsx
  src/pages/Inform/QandA.tsx
  src/pages/InformPage.tsx
Labels: 🚀 Feat

#71 대나무 숲 페이지 컴포넌트 개발
  src/App.tsx
  src/components/common/Header.tsx
  src/components/common/components.tsx
  src/components/community/ChatBox.tsx
  src/components/community/ChatList.tsx
  src/components/community/InputBox.tsx
  src/components/community/Intro.tsx
  src/components/main/Introduce.tsx
  src/images/community/arrowBottom.png
  src/images/community/community.png
  src/pages/Community/Community.tsx
  src/styles/effects.tsx
Labels: 🚀 Feat

#73 헤더 카테고리 수정 및 모바일 카테고리 개발
  src/@types/typs.ts
  src/App.tsx
  src/components/common/Header.tsx
  src/components/common/SearchBar.tsx
  src/data/category.json
  src/images/menu.svg
  src/images/search.svg
  src/pages/BoothPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/InformPage.tsx
  src/pages/ProgramPage.tsx
Labels: 🚀 Feat

#76 일부 모바일 기기에서 height 맞지 않는 오류 해결
  src/pages/CategoryPage.tsx
Labels: 🐛 BugFix

#79 Feature/78/add new community
  package.json
  src/@types/typs.ts
  src/components/community/ChatBox.tsx
  src/components/community/ChatList.tsx
  src/components/community/InputBox.tsx
  src/components/community/Required.tsx
  src/components/community/Toggle.tsx
  src/images/emoji/thinking.png
  src/pages/Login/Login.tsx
  src/utils/api.tsx
Labels: 🚀 Feat

#82 잘못된 페이지 접근 시에 예외 처리 페이지 생성 (#81)
  src/App.tsx
  src/images/emoji/not-found.svg
  src/pages/404/Error.tsx
Labels: 🚀 Feat

#86 대나무 숲 자동 업데이트 로직 및 통신 로직 추가 (#69)
  src/@types/typs.ts
  src/components/community/ChatList.tsx
  src/components/community/InputBox.tsx
  src/pages/Community/Community.tsx
Labels: 🚀 Feat

#89 fix : GNB 컴포넌트가 정상적으로 스크롤에 따라 작동하지 않는 현상 수정 (#67)
  src/App.tsx
  src/components/common/Header.tsx
Labels: bug, 🐛 BugFix
